### ISSUE TITLE
请问是否有办法可自定义正则匹配规则

### ISSUE THREAD

**Issue by Rainerhu** [m4yfly/vscode-maudit#2]
可以的话能否给出一些示例？因为会有开发的自定义封装的危险函数

**Comment by m4yfly** [comment]
参考vscode-maudit/config/php.en.json目录下相关json格式的定义，新增正则即可，然后按照Readme的说明重新编译后安装

**Comment by Rainerhu** [comment]
感谢，请问是否有方法增加更多类型的语言支持？

**Comment by m4yfly** [comment]
可以按照现有支持的语言及后缀格式的配置文件继续扩充，需要更改少部分加载规则的代码及插件支持的文件后缀配置等。可以简单看下vscode插件开发的相关文档然后自己按需求完善。

**Comment by Rainerhu** [comment]
好的，感谢
