### ISSUE TITLE
询问javaidea函数高亮方法

### ISSUE THREAD

**Issue by ljfhhh** [m4yfly/vscode-maudit#7]
师傅你好，我看到你之前提的洞的截图中，java内部方法和自定义方法颜色不一样
![image](https://github.com/user-attachments/assets/a97c7ebb-86b7-4278-8628-08e968c52462)
请问是怎么做到的，插件还是设置呢 可以告知一下吗

**Comment by m4yfly** [comment]
我有提什么洞吗？是不是找错人了？ @ljfhhh

**Comment by ljfhhh** [comment]
https://github.com/sunkaifei/FlyCms/issues/1 师傅这是您提的吧 @m4yfly

**Comment by m4yfly** [comment]
@ljfhhh 哦哦，漏洞时间太久没印象了。idea我没有进行额外设置，这是它默认暗色主题的显示效果。如果和你显示有差异的话，可以切换主题试试。

**Comment by ljfhhh** [comment]
非常感谢您的热心解答!但是我并没有达到您这样的效果。

**Comment by m4yfly** [comment]
@ljfhhh 那你要不截个图看看你现在怎么显示的？

**Comment by ljfhhh** [comment]
![image](https://github.com/user-attachments/assets/d62b5dbd-51df-4298-8b17-011e41ea1afe)
类似这种 内部方法和自定义方法颜色是相同的

**Comment by m4yfly** [comment]
看起来只是主题的问题
